FROM alpine/git as clone 
WORKDIR /app
RUN git clone {0} --verbose repo
WORKDIR repo
RUN git reset --hard {1}


FROM gradle:4.10.0-jdk8
USER gradle
RUN echo "starting code build"
WORKDIR /home/gradle
COPY --from=clone --chown=gradle /app/repo /home/gradle

{2}

RUN pwd
RUN ls -al

RUN gradle build --stacktrace