FROM alpine/git as clone 
WORKDIR /app
RUN git clone {0} --verbose repo
WORKDIR repo
RUN git reset --hard {1}


FROM openjdk:8-jdk-alpine
RUN apk add --no-cache curl tar bash procps

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \  
  && curl -fsSL -o /tmp/apache-maven.tar.gz https://apache.osuosl.org/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz \
  && echo "ce50b1c91364cb77efe3776f756a6d92b76d9038b0a0782f7d53acf1e997a14d  /tmp/apache-maven.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "/root/.m2"

RUN echo "starting code build"

WORKDIR /app
COPY --from=clone /app/repo /app

RUN pwd
RUN ls

RUN mvn compile