FROM node:latest

WORKDIR /usr/src

RUN git clone {0} --verbose repo
WORKDIR /usr/src/repo

RUN git reset --hard {1}
{2}

COPY nodejs/check_node_js.sh /usr/src

node --check ./hw.js
node --check ./hw2.js

RUN chmod +x /usr/src/check_node_js.sh
RUN /usr/src/check_node_js.sh
