FROM microsoft/dotnet:latest

RUN pwd
RUN ls
RUN git clone {0} --verbose repo
WORKDIR repo
RUN git reset --hard {1}
{2}
RUN dotnet restore
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/DockerCore.dll"]
